version: "3"

services:

  sample:
    container_name: clientapp
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
          DOCKER: DockerAssignment
      
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3020:3000
    environment:
      - CHOKIDAR_USEPOLLING=true