version: "3"
services:
  sample:
    container_name: dockerapp
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
          DOCKER: DockerAssignment
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3010:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
