FROM node:alpine as builder
WORKDIR /app
ARG DOCKER
ENV REACT_APP_DOCKER ${DOCKER}
COPY . ./
RUN npm install
RUN npm run build
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]